### ISSUE TITLE
Список устройств

### ISSUE THREAD

**Issue by vpropen** [wildcore-dms/issues#14]
добавить возможность активировать/деактивировать узел сети.. чтоб в случае времменного снятия узла (свитча), от не отображался в дашборде как недоступен.. и поллер не пытался его опрашивать..

**Comment by meklis** [comment]
Может убирать его с дашборда вообще?

**Comment by meklis** [comment]
Включение/отключение было заложено в системе, просто кнопки не было в веб-интерфейсе. 
Добавлена в изменении устройства, с версии 0.11.9
