### ISSUE TITLE
Очистка показників лічильника

### ISSUE THREAD

**Issue by vpropen** [wildcore-dms/issues#19]
D-Link DGS-1100-10/ME/A1
Firmware Version	V1.01.B102

не обнуляються показники трафіка і помилок при натисканні кнопки "очистити показники".. сповіщення про успішне виконання комманди відображуеться..

**Comment by meklis** [comment]
Есть ли возможность предоставить доступ к свитчу? телнет+snmp

**Comment by meklis** [comment]
Связано с багом #28
