### ISSUE TITLE
Huawei S2326TP-EI некоректне відображення mac-address

### ISSUE THREAD

**Issue by vpropen** [wildcore-dms/issues#20]
Huawei S2326TP-EI
Version 5.70

перши порт коммутатора в wildcore  відображається з 5-го

![1](https://user-images.githubusercontent.com/23407344/218265601-b88d96b1-039c-413c-8a3b-d4899f81a1df.png)
![2](https://user-images.githubusercontent.com/23407344/218265604-0f0931bd-7a47-4333-854a-82d3241fe0b4.png)

**Comment by meklis** [comment]
я так понимаю, зависит от прошивки или ревизии железяки. 
Нужен доступ к проблемной железке. 

Проверил по имеющимся свитчам этой модели - проблемы не увидел

**Comment by meklis** [comment]
Не смог найти подобных железок
