### ISSUE TITLE
C-DATA 1216 Error parse interface by ident='xge0/0/:2'

### ISSUE THREAD

**Issue by whooislogin** [wildcore-dms/issues#21]
Message: Error parse interface by ident='xge0/0/:2'
File: /www/vendor/meklis/switcher-core/src/Modules/CData/CDataAbstractModule.php:121
Trace:
#0 /www/vendor/meklis/switcher-core/src/Modules/CData/FdbTableConsole.php(97): SwitcherCore\Modules\CData\CDataAbstractModule->parseInterface('xge0/0/:2')
#1 /www/vendor/meklis/switcher-core/src/Modules/CData/FdbTableConsole.php(62): SwitcherCore\Modules\CData\FdbTableConsole->executeByInterfaces(Array)
#2 /www/vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(54) : eval()'d code(49): SwitcherCore\Modules\CData\FdbTableConsole->run(Array)
#3 /www/vendor/meklis/switcher-core/src/Switcher/Core.php(315): ProxyManagerGeneratedProxy\__PM__\SwitcherCore\Modules\CData\FdbTableConsole\Generated3d4cd0cb87cdd1be195b2a3b503a5cd1->run(Array)
#4 /www/src/SwitcherCore/SwitcherCore.php(355): SwitcherCore\Switcher\Core->action('fdb', Array)
#5 /www/src/SwitcherCore/SwitcherCore.php(109): WCAA\SwitcherCore\SwitcherCore->fromDeviceBatchCall(Array)
#6 /www/components/CDataInterfaces/Controllers/Controller.php(424): WCAA\SwitcherCore\SwitcherCore->fromDevice(Array)
#7 /www/components/CDataInterfaces/Controllers/Controller.php(484): WCC\CDataInterfaces\Controllers\Controller->callCore('fdb', Array, 'device')
#8 /www/src/Infrastructure/Poller/Pollers/FdbHistory.php(37): WCC\CDataInterfaces\Controllers\Controller->getFdbTable()
#9 /www/src/Infrastructure/Poller/PollerProcessor.php(323): WCAA\Infrastructure\Poller\Pollers\FdbHistory->run(Object(WCAA\Models\Devices\Device), Object(WCC\CDataInterfaces\Controllers\Controller))
#10 /www/src/Console/Poller/Poll.php(61): WCAA\Infrastructure\Poller\PollerProcessor->poll(Array, true)
#11 /www/vendor/symfony/console/Command/Command.php(298): WCAA\Console\Poller\Poll->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(WCAA\Console\Poller\Poll), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /www/console(43): Symfony\Component\Console\Application->run()
#16 {main}

**Comment by meklis** [comment]
какая версия wildcore?

**Comment by whooislogin** [comment]
Agent: 0.16.10-20230306

**Comment by meklis** [comment]
Проверьте на версии 0.17.x, возможно проблема ушла

**Comment by whooislogin** [comment]
помилка зникла
