### ISSUE TITLE
C-DATA 1108 помилка відкриття інтерфейсу

### ISSUE THREAD

**Issue by whooislogin** [wildcore-dms/issues#22]
при відкриті інтерфейсу  з'являється помилка ONU: pon1/4:2
Error loading info from API: Responses by module 'interface_counters' not found
або така ще може бути помилка
Error loading info from API: Cache not found by hash=8:pon_onts_optical:SUCCESS:3bed59d576f287f1d527139604acf079af32df14

**Comment by dj-black** [comment]
+1 до проблеми.
