### ISSUE TITLE
Добавить поддержку новых устройств

### ISSUE THREAD

**Issue by wildcore-dms** [wildcore-dms/issues#4]
* BDCOM GP3604-3616(B)
*  Huawei s2350-28
*  Huawei s5300 series
*  Huawei S3300 series
*  Huawei s9300 series
*  gpon olt zte c610

**Comment by meklis** [comment]
* Mikrotik: RB750, RB750UP, RB3011UiAS
* Alcatel-Lucent: OS6250-24M

**Comment by meklis** [comment]
> * BDCOM GP3604-3616(B)
> * Huawei s2350-28
> * Huawei s5300 series
> * Huawei S3300 series
> * Huawei s9300 series
> * gpon olt zte c610

BDCOM GP3604-3616(B) - добавлено с версии 0.13.1

**Comment by whooislogin** [comment]
D-Link DGS-1210-28 3.00.012
D-Link DGS-1210-16 2.03.001
TP-Link T2600G-18TS 1.0
TP-Link T1600G-28TS 3.0
TP-Link T1600G-28TS 1.0
TP-Link TL-SG2216 2.0
Cisco SG200-26

**Comment by whooislogin** [comment]
T2600G-18TS 1.0

**Comment by whooislogin** [comment]
T1600G-28TS 3.0

**Comment by whooislogin** [comment]
DGS-1210-16 2.03.001

**Comment by meklis** [comment]
> D-Link DGS-1210-28 3.00.012 D-Link DGS-1210-16 2.03.001 TP-Link T2600G-18TS 1.0 TP-Link T1600G-28TS 3.0 TP-Link T1600G-28TS 1.0 TP-Link TL-SG2216 2.0 Cisco SG200-26

Нужно доступ к свитчам. Маякните в telegram, если есть возможность предоставить - https://t.me/WildcoreSupport
