### ISSUE TITLE
Уведомления на основе зависимости устройств, что бы исключить лишние сообщения

### ISSUE THREAD

**Issue by wildcore-dms** [wildcore-dms/issues#8]
Подумать в сторону оптимизации уведомлений пингера.     
Например если рвется кабель между нас. пунктами - приходит триллион сообщений что каждая железка упала. Логичнее былобы сделать логику зависимостей - если упал транспортный коммутатор на удаленной площадке - достаточно одного этого уведомления.     
В mikrotik the dude это реализовано.     
В настройках каждого устройства выбирается родительское устройство.

**Comment by meklis** [comment]
Реализовано в версии 0.16.
Необходимо использовать компонент линки (прокинуть линки) + включить проверку аплинка в настройках уведомлений
